#include "batgen.h"
#include <fstream>
#include <cstring>

// 修复：统一为CP_UTF8，与scanner.cpp中的WToA一致，确保SaveBatchFile的UTF8→GB2312转换正确
static std::string WToA(const std::wstring& ws) {
    if (ws.empty()) return "";
    int len = WideCharToMultiByte(CP_UTF8, 0, ws.c_str(), -1, nullptr, 0, nullptr, nullptr);
    if (len <= 0) return "";
    std::string s(len - 1, '\0');
    WideCharToMultiByte(CP_UTF8, 0, ws.c_str(), -1, &s[0], len, nullptr, nullptr);
    return s;
}

// Check if system language is Chinese
static bool IsChineseSystem() {
    LANGID langId = GetUserDefaultUILanguage();
    WORD primary = PRIMARYLANGID(langId);
    return primary == LANG_CHINESE || primary == LANG_CHINESE_SIMPLIFIED
        || primary == LANG_CHINESE_TRADITIONAL || langId == 0x0804
        || langId == 0x0404 || langId == 0x0c04 || langId == 0x1004;
}

std::string GenerateBatch(const ScanResult& result, const BatchOptions& options) {
    std::string sb;
    std::string fname = WToA(result.fileName);
    bool zh = IsChineseSystem();

    // Header comments
    if (options.includeComments) {
        sb += "@REM ============================================================\r\n";
        sb += zh ? "@REM 静默安装脚本 - 由大内静探生成\r\n"
                : "@REM Silent install script - generated by SilentParamQuery\r\n";
        sb += "@REM " + (zh ? std::string("文件: ") : std::string("File: ")) + fname + "\r\n";
        sb += "@REM " + (zh ? std::string("安装器: ") : std::string("Installer: ")) + result.installerFullName + "\r\n";
        sb += "@REM " + (zh ? std::string("检测方式: ") : std::string("Detection: ")) + result.detectedBy + "\r\n";
        sb += "@REM ============================================================\r\n";
        sb += "\r\n";
    }

    sb += "@echo off\r\n";
    sb += zh ? "chcp 936 >nul 2>&1\r\n" : "chcp 65001 >nul 2>&1\r\n";
    sb += "\r\n";

    // UAC elevation
    if (options.includeUac) {
        sb += zh ? "@REM 请求管理员权限\r\n"
                : "@REM Request admin privileges\r\n";
        sb += "NET SESSION >nul 2>&1\r\n";
        sb += "IF %ERRORLEVEL% NEQ 0 (\r\n";
        sb += zh ? "    echo 正在请求管理员权限...\r\n"
                : "    echo Requesting admin privileges...\r\n";
        sb += "    powershell -Command \"Start-Process '%~f0' -Verb RunAs\"\r\n";
        sb += "    exit /b\r\n";
        sb += ")\r\n";
        sb += "\r\n";
    }

    // Installer path
    sb += "set \"INSTALLER=%~dp0" + fname + "\"\r\n";
    sb += "\r\n";

    // Error handling preamble
    if (options.includeErrorHandling) {
        sb += "if not exist \"%INSTALLER%\" (\r\n";
        sb += zh ? "    echo [错误] 找不到安装文件: %INSTALLER%\r\n"
                : "    echo [ERROR] Installer not found: %INSTALLER%\r\n";
        sb += "    pause\r\n";
        sb += "    exit /b 1\r\n";
        sb += ")\r\n";
        sb += "\r\n";
        sb += "echo ============================================================\r\n";
        sb += zh ? "echo  正在安装: " + fname + "\r\n"
                : "echo  Installing: " + fname + "\r\n";
        sb += (zh ? "echo  类型: " : "echo  Type: ") + result.installerFullName + "\r\n";
        sb += "echo ============================================================\r\n";
        sb += "\r\n";
    }

    // Install command
    std::string installCmd = result.silentCommand;
    // Replace {file} with %INSTALLER%
    {
        size_t pos = installCmd.find("{file}");
        if (pos != std::string::npos)
            installCmd.replace(pos, 6, "%INSTALLER%");
    }

    // Log mode override
    if (options.includeLog) {
        std::string logPath = "%~dp0install_log.txt";
        if (result.installerType == "MSI" || result.installerType == "WiXMSI") {
            installCmd = "msiexec /i \"%INSTALLER%\" /qn /norestart /l*v \"" + logPath + "\"";
        } else if (result.installerType == "InnoSetup") {
            installCmd = "\"%INSTALLER%\" /VERYSILENT /SP- /LOG=\"" + logPath + "\"";
        } else if (result.installerType == "InstallShield" || result.installerType == "InstallScript") {
            installCmd = "\"%INSTALLER%\" /s /v\"/qn /l*v " + logPath + "\"";
        } else if (result.installerType == "BitRockInstallBuilder") {
            installCmd = "\"%INSTALLER%\" --mode unattended --debuglevel 4";
        }
    }

    sb += zh ? "echo 正在安装...\r\n" : "echo Installing...\r\n";
    sb += installCmd + "\r\n";
    sb += "\r\n";

    // Error checking
    if (options.includeErrorHandling) {
        sb += "if %ERRORLEVEL% EQU 0 (\r\n";
        sb += zh ? "    echo [成功] 安装完成\r\n"
                : "    echo [SUCCESS] Installation complete\r\n";
        sb += ") else (\r\n";
        sb += zh ? "    echo [失败] 安装出错，错误代码: %ERRORLEVEL%\r\n"
                : "    echo [FAILED] Installation error, code: %ERRORLEVEL%\r\n";
        sb += "    pause\r\n";
        sb += "    exit /b %ERRORLEVEL%\r\n";
        sb += ")\r\n";
        sb += "\r\n";
    }

    if (options.includeLog) {
        sb += zh ? "echo 日志已保存到: install_log.txt\r\n"
                : "echo Log saved to: install_log.txt\r\n";
    }

    sb += zh ? "echo 安装完成。\r\n" : "echo Installation complete.\r\n";
    sb += "exit /b 0\r\n";

    return sb;
}

bool SaveBatchFile(const std::string& content, const std::wstring& filePath) {
    // 中文系统用GB2312(CP936)，其他系统用UTF-8+BOM确保兼容
    FILE* f = _wfopen(filePath.c_str(), L"wb");
    if (!f) return false;

    if (IsChineseSystem()) {
        // Convert UTF-8 content to GB2312 (code page 936) for Chinese CMD compatibility
        int wideLen = MultiByteToWideChar(CP_UTF8, 0, content.c_str(), -1, nullptr, 0);
        if (wideLen <= 0) { fclose(f); return false; }
        std::wstring wide(wideLen - 1, L'\0');
        MultiByteToWideChar(CP_UTF8, 0, content.c_str(), -1, &wide[0], wideLen);

        int ansiLen = WideCharToMultiByte(936, 0, wide.c_str(), -1, nullptr, 0, nullptr, nullptr);
        if (ansiLen <= 0) { fclose(f); return false; }
        std::string ansi(ansiLen - 1, '\0');
        WideCharToMultiByte(936, 0, wide.c_str(), -1, &ansi[0], ansiLen, nullptr, nullptr);

        fwrite(ansi.data(), 1, ansi.size(), f);
    } else {
        // Non-Chinese: save as UTF-8 with BOM
        unsigned char bom[] = {0xEF, 0xBB, 0xBF};
        fwrite(bom, 1, 3, f);
        fwrite(content.data(), 1, content.size(), f);
    }

    fclose(f);
    return true;
}
